name: build
on:
    push:
        branches:
            - master
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Setup Sbt and Build
              id: sbt
              uses: lokkju/github-action-sbt@14-1.3.0-2.13.0
              with:
                  commands: fullOptJS::webpack
                  sbt_project_directory: ./
            - name: Install Dependencies
              working-directory: ts
              run: npm install
            - name: npm build
              working-directory: ts
              run: npm run prod
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  PROJECT_ID: codedocs-e3aeb
